### ISSUE TITLE
how can i get drag folder path use prima::inputline on my win7

### ISSUE THREAD

**Issue by StevenCoober** [dk/Prima#103]
use Encode;
use Prima qw(Application);
use Prima::MsgBox qq(input_box message);
use Prima qw(Edit InputLine Application);
use Proc::ProcessTable;
$w = Prima::MainWindow->new(
    text     => "node",
    size     => [ 300, 350],
    centered => 1,
);
$project_input = $w->insert(
    'Prima::InputLine',
    text => decode("gbk", ''),
    pack => { fill => 'x', side => 'top', pad => 10 },
    dndAware => 1,
    onDragBegin => sub {
        my ($self, $clipboard, $action, $modmap, $x, $y, $ref) = @_;
        my $string = $clipboard-> text;
        my $image  = $clipboard-> image;
        print("how can i get drag folder path on my win7");
    }
    
);
run Prima;

**Comment by StevenCoober** [comment]
can anyone help me?

**Comment by dk** [comment]
There seems to be something fishy with the whole DND in windows, I just tried every small program I could find, including notepad.exe, to accept drop files from the file explorer and it just doesn't work. IT looks like this is could be security-related?

https://www.elevenforum.com/t/drag-and-drop-while-running-as-admin.16916/

Not even the simples DND example from here https://github.com/alexGuntha/mindragndropwin cannot work with explorer.
Very. very strange

**Comment by dk** [comment]
I hacked this, https://github.com/dk/Prima/commit/04a115c5e571ddea5b368507f7a9d6acffc1cf89, try to see if that helps you though - I got it working on an old emulated windows 7

**Comment by StevenCoober** [comment]
Thanks a lot for your quick response and the fix 😊

**Comment by StevenCoober** [comment]
It works for me on my old win7 😊

**Comment by dk** [comment]
shall we close the issue then?

**Comment by StevenCoober** [comment]
yes
