### ISSUE TITLE
Ticket (issues) repository

### ISSUE THREAD

**Issue by PhilterPaper** [dk/Prima#105]
Per RT 149672 (closed), you said

> BTW I'd prefer having bugs here https://github.com/dk/Prima/issues as I think that the RT interface doesn't have that good integration with the source code...

Note that your CPAN package is still set up to use the RT repository. It's been a while, so I don't remember the exact details, but it's possible to change it to point to the GitHub repository for issues. That way you won't get any more tickets in RT.

**Comment by dk** [comment]
good point, thank you
