### ISSUE TITLE
Error in img/codec_heif.c - line  180

### ISSUE THREAD

**Issue by NorbertXYZ** [dk/Prima#112]
Compilation broke, because after a "default:" there was missing a "continue;" statement... :-)

Using FreeBSD 13.2 and Prima 1.72

**Comment by dk** [comment]
Did you check the latest git checkout?

**Comment by NorbertXYZ** [comment]
I checked against the latest from git repository - you are right - and sorry...  would it be good to make (also) a new version to download?  By the way - I like your Prima :-)  Very fast - i am working on a project with it :-)  All the best, Norbert

**Comment by dk** [comment]
Thanks! Prima releases are roughtly 3 months apart, but you can also grab a 1.71 or 1.70 if you need a tarball.
