### ISSUE TITLE
t/Object/GP.t fails (Ubuntu 24.04, arm64)

### ISSUE THREAD

**Issue by eserte** [dk/Prima#119]
I see the following failure on several self-compiled perls on an Ubuntu 24.04/arm64 system:
```
#   Failed test 'text_out'
#   at t/Object/GP.t line 325.
#     '5'
#         >
#     '5'
# Looks like you failed 1 test of 118.
t/Object/GP.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/118 subtests 
```

**Comment by dk** [comment]
Yes I also see that on other arm64/armel/armhf reports from cpantesters... but couldn't reproduce on my qemu armhf setup. If you have a virtual machine snapshot with this kindly share!

**Comment by eserte** [comment]
Hi Dmitry, see PM.

**Comment by eserte** [comment]
Actually it seems to depend on the X11 environment. Using Xvfb (on the test system with `xvfb-run cpan_smoke_modules -pv 5.40.0 Prima`) runs fine. With vncserver (on the test system `cpan_smoke_modules -pv 5.40.0 Prima -vnc`) it fails with the error message above (sometimes it seems that the got value is 3). However I use vncserver also on other systems (older Ubuntus, Debian...) without any failures.

**Comment by dk** [comment]
fixed, thank you very much for your help Slaven!
