### ISSUE TITLE
Embed Browser engine inside Prima::Window

### ISSUE THREAD

**Issue by vikasnkumar** [dk/Prima#124]
Hi @dk 
I want to render some HTML & Javascript code inside a Prima Window. I have been doing it with Browser::Open, opening a browser to do that but it is not ideal. Was wondering if you know of a way to deal with this, I need to render the HTML/JS inside a window in Prima. 

What suggestions do you have ?

thanks

**Comment by dk** [comment]
None easy, unfortunately. I thought about it many times and every time I shot it down because implementation price is high and the demand is zero. There are external C libraries that can render html and css and these can be harnessee with XS with an effort, but JS and subsequently DOM manipulation is quite anothet beast. Gtk browser widget can do it, I think

**Comment by vikasnkumar** [comment]
You mean https://www.webkitgtk.org/ ? The other option is Chromium Embedded Framework. If I were to extend `Prima::Window` to `Prima::Window::Chromium` or `Prima::Window::WebkitGTK` where do I start ? Let's assume it is a new stand-alone package for now. is there an example package code-base i can leverage to get started quickly ?

**Comment by dk** [comment]
Either one is good. Prima has an ability to host a non-native x11 window (and win32 too), so this would be rather a question for either webgtk or chromium to create one in the window, which system handle is returned by Prima::Window->get_handle. Next, the even loop, this is harder. With gtk I only managed to befriend it with Prima for file-opening dialogs, that run in a modal execution loop and don't mix much with Prima's loop. One needs to find gtk/gio/glib function that yields a single gtk slice, and mix it with Prima's event loop. I didnt try that. The same is with chromium.

**Comment by vikasnkumar** [comment]
I will investigate in the next few weeks and get back to you.

**Comment by dk** [comment]
I cooked up a small C program that more or less does the same as the GPExtra.t . I wounder if you could run it on your setup and see if it prints same as 
[fpx-test.tar.gz](https://github.com/user-attachments/files/17702466/fpx-test.tar.gz)
in the file named `good` ?
