### ISSUE TITLE
Text editor selection is weird

### ISSUE THREAD

**Issue by run4flat** [dk/Prima#37]
Text selection gives the wrong result due to incorrect logic in `selection_to_physical`. I am not sure what the function is trying to achieve, so I am not sure how to fix things.

To reproduce the problem, run the text editor example script (editor.pl). Type `abc` in the first row and `def` in the second row. Select from `c` to `d`, over the newline (Shift-Down-Left). Copy, then paste into another text editor. I get `bc\nde` instead of the expected `c\nd`.

I am running v1.44, but it persists in the latest repository, I believe.

**Comment by run4flat** [comment]
Here is an example of the selection:
![editor](https://cloud.githubusercontent.com/assets/260215/12127760/012c7848-b3c7-11e5-9e84-28c5c07d0d9f.png)

and the result of the paste into another text editor:
![pasted-results](https://cloud.githubusercontent.com/assets/260215/12127772/0bd8d02a-b3c7-11e5-8152-075968f92cfd.png)

**Comment by dk** [comment]
Hi David,

I can't reproduce the exact results you're getting, but mine resuls are weird too. I think I've fixed it.
The problem the function was trying to fix was the case for newly implemented bidirectional edit.
Please take a look if it works for you.

/dk
