### ISSUE TITLE
undefined symbol: DGifOpen in Mageia

### ISSUE THREAD

**Issue by MaxPerl** [dk/Prima#47]
Hello,

Unter Mageia Linux 5.1 I get the following error, when trying the examples (fonntdlg.pl, keys.pl, label.pl):

perl: symbol lookup error: /usr/lib/perl5/vendor_perl/5.20.1/x86_64-linux-thread-multi/auto/Prima/Prima.so: undefined symbol: DGifOpen

The problem occurs with the Prima version of Mageia, the newest CPAN version and the actual github branch.

Best wishes,
Max

**Comment by dk** [comment]
I could reproduce the error. I'll work on a fix a bit longer. Meanwhile, removing libungif.so from the system and recompiling Prima should work.

**Comment by dk** [comment]
I believe this should fix it

**Comment by MaxPerl** [comment]
Dear Dimitry,
You are fantastic! Everything works now great!
Thanks a lot for everything...
Max
