### ISSUE TITLE
While copying the text to the editor misspelled some of the words

### ISSUE THREAD

**Issue by akuks** [dk/Prima#60]
While copying the text to the editor misspelled some of the words in the edit.

[Actual Result]

While copying the headline from the [url](https://aajtak.intoday.in/story/coronavirus-sonu-sood-helps-migrant-workers-pregnant-lady-names-child-after-actor-tmov-1-1195416.html
)  to the editor misspelled some the words. 

Refer the first line of the [image](https://user-images.githubusercontent.com/12954663/83225204-de9ca780-a19c-11ea-9190-a9649ab0fc48.png)

[Expected Result]
Text should match the headlines of the link.

**Comment by dk** [comment]
This happens if Prima is compiled without harfbuzz or without Xft. Added warnings about this in Makefile.PL
