### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by jan-herout** [dk/Prima#61]
```
#   Failed test 'send'
#   at t/Widget/Mouse.t line 35.

#   Failed test 'post'
#   at t/Widget/Mouse.t line 43.

#   Failed test 'click'
#   at t/Widget/Mouse.t line 57.

#   Failed test 'doubleclick'
#   at t/Widget/Mouse.t line 63.

#   Failed test 'simulated movement'
#   at t/Widget/Mouse.t line 84.
```

**Comment by dk** [comment]
Yeah, that happens once in a while. F.ex. under virtualbox or rdesktop environments. It's not even serious, so if you can, disregard.

**Comment by jan-herout** [comment]
It seems you are correct. Examples from Metacpan run normally.

**Comment by dk** [comment]
However, if you can _consistently_ reproduce the issue, I should very much like to know all the details, i.e. windows version, how it was run, virtual box/remote desktop, anything -- because it's a bit annoying and volatile scenario I couldn't put a finger on
