### ISSUE TITLE
SIGABRT from CPANTesters

### ISSUE THREAD

**Issue by mohawk2** [dk/Prima#63]
I see you've added CI, great stuff! See https://www.cpantesters.org/cpan/report/d4ae9744-c98e-11ec-95f8-e64f08875e30, excerpt:

```
t/Object/Application.t .. ok
perl: unix/clipboard.c:167: prima_clipboard_kill_item: Assertion `PL_valid_types_RV[SvTYPE(_svrv) & SVt_MASK]' failed.
t/Object/Clipboard.t .... 
Failed 3/11 subtests 
# ...
Test Summary Report
-------------------
t/Object/Clipboard.t  (Wstat: 134 (Signal: ABRT, dumped core) Tests: 8 Failed: 0)
  Non-zero wait status: 134
  Parse errors: Bad plan.  You planned 11 tests but ran 8.
```

**Comment by dk** [comment]
Yeah, I've seen that too, it is fixed now. It is though a very insignificant corner case so is safe to use.

**Comment by mohawk2** [comment]
May I ask if there's a test to capture that it's fixed? And whether you're going to release the updated version?

**Comment by dk** [comment]
There's the same test that failed, t/Object/Clipboard.t , and it doesn't fail anymore neither on github actions nor on my test machines. I don't plan to release the next version in at least 3 months and probably more - the reason is that I release only when there is a significant functionality change, and so far there isn't much

**Comment by mohawk2** [comment]
My approach is that fewer test-failures is sufficient to justify a release - it's not like we get charged money for them. If the goal is stability, then dev-releases would help. Also, working on a branch so that all the commits make sense (with frequent rebasing etc) is another technique I have found beneficial.

**Comment by dk** [comment]
I hear you. Should we close this issue then?

**Comment by mohawk2** [comment]
Let's do.
