### ISSUE TITLE
CALLBACK definition on cl

### ISSUE THREAD

**Issue by jddurand** [dk/Prima#68]
As per https://github.com/dk/Prima/commit/dcaf866bbc57bb1fffc6c2a7eae938b0b9e1dcdc#r91157551 the CALLBACK definition is wrong, making Prima use __cdecl calling convention instead of __stdcall.

**Comment by dk** [comment]
fixed now, please check if that works for you

**Comment by jddurand** [comment]
Yes, that works fine - many thanks.

**Comment by jddurand** [comment]
Closing the issue
