### ISSUE TITLE
Prima fails test on Debian Bullseye

### ISSUE THREAD

**Issue by vikasnkumar** [dk/Prima#76]
Hi @dk 

I am running the github version of Prima from Issue #75 . 

I have all the following installed: libgtk-3-dev libgktmm-3.0-dev libheif-dev libwebp-dev libxpm-dev libjpeg-dev libpng-dev libtiff-dev gnuplot

Then I download the Github code, run `perl Makefile.PL` and `make` and `make test`.

The test that fails is `t/Widget/Window.t` and it says `Failed test 'show'` and `Failed test 'hide'`. The window that gets opened does not hide and I think that's the issue.

I have XFCE as my window manager, although I do not think it matters. Any GUI windowing system should work.

Please advise.

**Comment by dk** [comment]
Hi Vikas,

I couldn't make my ubuntu start a xfce session, but I could fix that on mwm.
So I advise to check if that fix works on your xfce

/dk

**Comment by vikasnkumar** [comment]
Hi @dk 
This fix worked and all my tests passed. Thank you. Happy New Year !
