### ISSUE TITLE
Facing Problem Installing prima in UBUNTU   Can't locate Prima/sys/Gencls.pm in @inc (you may need to install the Prima::sys::Gencls module) 

### ISSUE THREAD

**Issue by faraziAnindo** [dk/Prima#83]
perl Makefile.PL 
Can't locate Prima/sys/Gencls.pm in @INC (you may need to install the Prima::sys::Gencls module) (@INC contains: . /home/a/anaconda3/lib/perl5/5.32/site_perl /home/a/anaconda3/lib/perl5/site_perl /home/a/anaconda3/lib/perl5/5.32/vendor_perl /home/a/anaconda3/lib/perl5/vendor_perl /home/a/anaconda3/lib/perl5/5.32/core_perl /home/a/anaconda3/lib/perl5/core_perl) at Makefile.PL line 20.
BEGIN failed--compilation aborted at Makefile.PL line 20.

**Comment by faraziAnindo** [comment]
@dk

**Comment by dk** [comment]
Is the file Prima/sys/Gencls.pm itself there? Are the permissions correct? Could you post ```ls -l Prima/sys/Gencls.pm```?

**Comment by faraziAnindo** [comment]
![Screenshot from 2023-02-25 14-41-10](https://user-images.githubusercontent.com/74466258/221347789-6f72505c-954f-4ef3-bc04-9092638a64f2.png)


here is the screenshot, where is the distro directory can you please elaborate it.

**Comment by dk** [comment]
This is not Prima problem. I suggest you follow a tutorial how to install a perl module on linux, f ex this https://www.ibm.com/docs/en/product-master/12.0.0?topic=perl-installing-modules or this https://ostechnix.com/how-to-install-perl-modules-on-linux/ .

**Comment by faraziAnindo** [comment]
Thanks i installed the perl module using sudo cpan

**Comment by faraziAnindo** [comment]
i installed the Prima::sys::Gencls module but it still showing the same problem when i run perl Makefile.PL. please help
