### ISSUE TITLE
Error about gif support in ActivePerl 5.36

### ISSUE THREAD

**Issue by slalaurette** [dk/Prima#84]
Hi! This is a very old issue that I found years ago, was unable to solve, and I'm facing again after trying to use Prima with a new ActivePerl installation (using the new "ActiveState Platform" version and the "state tool" to install and update modules). 

Whenever I `use Prima;` in a script, I get this error message in the console as the script starts executing: 

`Failed to load standard bitmap 'c:/Users/sebastian/AppData/Local/activestate/cache/fe8afb71/site/lib/Prima/sys/win32/sysimage.gif':No appropriate codec found. Did you compile Prima with GIF support?`

Then, of course, I can't use any gif images in my script. 

I tried uninstalling Prima, installing Prima::codecs::win64, and then reinstalling Prima, just in case. But, alas, it didn't work. 

I see there are precompiled binaries for other Perls, but not for ActivePerl, so I wonder if there is a way I can get one, or instruct ActiveState, somehow, to build Prima with gif support. 

I can't switch to Strawberry Perl for several reasons, one of them being the future of that particular Perl looks dubious (the latest version being 5.32).

Any help will be appreciated!

**Comment by dk** [comment]
Hello

Some months ago I was trying to see what is the status with ActivePerl, and I couldn't do much with it as they replaced their PPM with the state tool, which refuses to install either MinGW (as it used to do), or GCC -- a total mess!

I'm not sure how you managed to install gcc there, but _if_ you did that, you can try to use it to install libgif from source from https://giflib.sourceforge.net/ . Or probably you can copy the needed files from Prima::codecs::win64 as try to re-run Makefile.PL and see the error messages in makefile.log, to see if it could locate these.

Sorry couldn't be of much help because I couldn't make ActiveState work properly

/dk

**Comment by dk** [comment]
And this is also official, after I asked: https://community.activestate.com/t/how-to-install-gcc-and-or-mingw/10993/2 . So no, ActivePerl is not really a usable platform so far.

**Comment by slalaurette** [comment]
Well, that really sucks. But thank you for checking with the ActiveState people!

I'll see if I can keep a separate installation of Strawberry just to be able to use Prima with it. 

If that's not feasible, will I just be unable to use gif images in my scripts, or are there other, more important things that will fail?

**Comment by dk** [comment]
I have an idea I'd like to check out later, basically to augment an activestate installation with a mingw distro, possibly even one from strawberry. If that will be a success, I shall make a guideline/howto about it. Let's not close this ticket, I'd like to have this addressed

**Comment by dk** [comment]
Just recently I got to know that there are releases from Strawberry perl, just not on the frontpage - apparently they lost access to it. But the releases are there and are just fine: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases , I tried 5.38 and it's working fine with Prima, although libwebp support is not there. If you need that too, you're welcome to ++ this issue as well: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/125

Anyhow, I would urge you to try them see if they work for your project too.
