### ISSUE TITLE
Cannot open include/apricot.h:No such file or directory

### ISSUE THREAD

**Issue by faraziAnindo** [dk/Prima#85]
root@a:/home/a/Desktop/BPGA-1.3-linux-x86_64-0-0-0# perl Makefile.PL 
Version: 1.68
Flavor: linux.x86_64
Build: Prima-1.68-linux.x86_64-5.34.0
Compiler: gcc
Checking if can compile... yes
Checking if can link... yes
Checking if can compile with OpenMP... yes
Cannot open include/apricot.h:No such file or directory

Hey @dk thanks for solving the previous problem, this time this new problem raised while running perl Makefile.PL .
Thanks in advance

**Comment by faraziAnindo** [comment]
@dk can you please help

**Comment by dk** [comment]
If you installed prima with cpan you dont need to build it, it should be already installed and usable

**Comment by dk** [comment]
closed:not a Prima error
