### ISSUE TITLE
failed install on strawberry due to mouse test Win10 strawberry 5.28

### ISSUE THREAD

**Issue by osascruz** [dk/Prima#89]
Strawberry** Perl (64-bit) 5.28.1.1-64bit  windows 10
is it notmal to fail the install because of the  Mouse test ?
should I force the install ? thank you :)

`t/Widget/Mouse.t ........ 1/11
   Failed test 'simulated movement'
   at t/Widget/Mouse.t line 90.
 Looks like you failed 1 test of 11.
t/Widget/Mouse.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/11 subtests
t/Widget/Move.t ......... ok
t/Widget/Paint.t ........ ok
[...]
Test Summary Report
-------------------
t/Widget/Mouse.t      (Wstat: 256 (exited 1) Tests: 11 Failed: 1)
  Failed test:  11
  Non-zero exit status: 1
Files=48, Tests=11916, 27 wallclock secs ( 0.81 usr +  0.16 sys =  0.97 CPU)
Result: FAIL
Failed 1/48 test programs. 1/11916 subtests failed.
gmake: *** [Makefile:1847: test_dynamic] Error 255
  KARASIK/Prima-1.68002.tar.gz
  C:\STRAWB~1\c\bin\gmake.exe test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports KARASIK/Prima-1.68002.tar.gz
Stopping: 'install' failed for 'Prima'.`

**Comment by dk** [comment]
Nevermind, it fails once in a while. It us completely safe to install
