### ISSUE TITLE
charOffset description

### ISSUE THREAD

**Issue by reinierma** [dk/Prima#92]
The description of charOffset in https://metacpan.org/pod/Prima::InputLine is not clear for me:

charOffset INTEGER
    Selects the position of the cursor in clusters starting from the beginning of visual text.

Notice the following:   
1. charOffset **gets** the current position of the cursor
2. charOffset N **sets** the cursor at position N of a text string (if present)

IMHO the word 'Selects' in your description could be better replaced by 'Gets and sets' (cf. function names GetCurPos and SetCurPos in some languages)

**Comment by dk** [comment]
Hi Reinier,

Thank you this is one step closer! Now, would you kindly make a pull request where it description would mention #92 verbatim? That way github can link the commit with the issue

/dk
