### ISSUE TITLE
Fails to install "no makefile"

### ISSUE THREAD

**Issue by haxmeister** [dk/Prima#98]
### Received this error trying to install the new Prima:
Please note that the previous version is already installed on this system and has been tested and working

localhost:/home/haxmeister # cpan Prima
Reading '/root/.cpan/Metadata'
  Database was generated on Wed, 06 Sep 2023 21:54:05 GMT
CPAN: HTTP::Tiny loaded ok (v0.086)
CPAN: Net::SSLeay loaded ok (v1.92)
CPAN: IO::Socket::SSL loaded ok (v2.083)
Fetching with HTTP::Tiny:
https://cpan.org/authors/01mailrc.txt.gz
Reading '/root/.cpan/sources/authors/01mailrc.txt.gz'
CPAN: Compress::Zlib loaded ok (v2.204)
............................................................................DONE
Fetching with HTTP::Tiny:
https://cpan.org/modules/02packages.details.txt.gz
Reading '/root/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Fri, 08 Sep 2023 00:17:01 GMT
CPAN: HTTP::Date loaded ok (v6.06)
............................................................................DONE
Fetching with HTTP::Tiny:
https://cpan.org/modules/03modlist.data.gz
Reading '/root/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /root/.cpan/Metadata
Running install for module 'Prima'
CPAN: Digest::SHA loaded ok (v6.04)
Checksum for /root/.cpan/sources/authors/id/K/KA/KARASIK/Prima-1.70.tar.gz ok
CPAN: YAML loaded ok (v1.30)
CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
CPAN: Parse::CPAN::Meta loaded ok (v2.150010)
CPAN: CPAN::Meta loaded ok (v2.150010)
CPAN: Module::CoreList loaded ok (v5.20230520)
Configuring K/KA/KARASIK/Prima-1.70.tar.gz with Makefile.PL
Version: 1.70
Flavor: linux.x86_64
Build: Prima-1.70-linux.x86_64-5.38.0
Compiler: gcc
Checking if can compile... yes
Checking if can link... yes
Checking if can compile with OpenMP... yes
Checking for presence of io.h... no
Checking for presence of unistd.h... yes
Checking for presence of strings.h... yes
Checking for presence of sys/types.h... yes
Checking for presence of type int8_t... yes
Checking for presence of type int16_t... yes
Checking for presence of type int32_t... yes
Checking for presence of type int64_t... yes
Checking for presence of type uint8_t... no
Checking for presence of sys/bitypes.h... yes
Checking for presence of type uint8_t... no
Checking for presence of sys/inttypes.h... no
Checking for presence of stdint.h... yes
Checking for presence of type uint8_t... yes
Checking for presence of type uint16_t... yes
Checking for presence of type uint32_t... yes
Checking for presence of type uint64_t... yes
Checking for presence of type u_int8_t... yes
Checking for presence of type u_int16_t... yes
Checking for presence of type u_int32_t... yes
Checking for presence of type u_int64_t... yes
Checking for presence of type ssize_t... yes
Checking for presence of sys/ipc.h... yes
Checking for presence of sys/shm.h... yes
Checking for function strcasecmp... no
Checking for presence of string.h... yes
Checking for function stricmp... no
Checking for function strncasecmp... no
Checking for function strnicmp... no
Checking for function strcasestr... no
Checking for presence of stdio.h... yes
Checking for function snprintf... no
Checking for function _snprintf... no
Checking for presence of stdlib.h... yes
Checking for function reallocf... no
Checking for function bzero... no
Checking for function memmem... no
Checking for function strlcpy... no
Checking for function eaccess... no
Checking for inline... inline
Checking for glibc... yes
Determining dl_load_flags... 0x01
Checking for pkg-config... yes
Checking for fribidi using pkg-config...no
Checking for libthai using pkg-config...no
Checking for x11 using pkg-config...no
Prima needs package with x11 development file for compilation! Please install it with your system installer tool.

** Warning: fribidi is needed for bidirectional text.
Prima compiled without fribidi will not be able
to handle right-to-left text, f.ex. Arabic or Hebrew.
Consider fixing your installation.

** Warning: libthai is needed for proper breaking of thai text.
Consider fixing your installation.

No 'Makefile' created  KARASIK/Prima-1.70.tar.gz
  /usr/bin/perl Makefile.PL -- NOT OK

### Perl version:
localhost:/home/haxmeister # perl -v

This is perl 5, version 38, subversion 0 (v5.38.0) built for x86_64-linux-thread-multi

### System:
Operating System: openSUSE Tumbleweed 20230828
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.11-1-default (64-bit)
Graphics Platform: X11
Processors: 6 × Intel® Core™ i5-8500 CPU @ 3.00GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630
Manufacturer: HP
Product Name: HP EliteDesk 800 G4 SFF

**Comment by dk** [comment]
You need the x11 libs:

> Prima needs package with x11 development file for compilation! Please install it with your system installer tool.

**Comment by dk** [comment]
(README lists all the other prerequisitws needed, too)
